version: '3.8'

services:
  frontend:
    image: chaymae888/my-frontend:1.0
    ports:
      - "3000:3000"
    networks:
      - myoverlaynetwork
    depends_on:
      - backend
    deploy:
      replicas: 2  
      resources:
        limits:
          cpus: "0.5"  
          memory: 512M  
      restart_policy:
        condition: on-failure

  backend:
    image: chaymae888/my-backend:1.0
    ports:
      - "8080:8080"
    networks:
      - myoverlaynetwork
    depends_on:
      - db
    deploy:
      replicas: 2  
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  db:
    image: chaymae888/my-postgres:1.0
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    networks:
      - myoverlaynetwork
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - myoverlaynetwork
    depends_on:
      - frontend
      - backend
      - db
    


networks:
  myoverlaynetwork:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
